POST {{panel_api_url}}/auth/setup HTTP/1.1
Content-Type: application/json

{
  "app_id": "{{panel_app_id}}",
  "lang": "{{lang}}",
  "source": "{{source}}",
  "env": "{{env}}",
  "v": "{{version}}",
  "data": {
    "username": "admin",
    "password": "123456",
    "operator": 1,
    "prefix": "99450",
    "number": "6666636",
    "email": "tural.ilyasov@bk.ru",
    "fullname": "Tural Ilyasov",
    "gender": "male",
    "birth": "1990-03-19"
  }
}