POST {{panel_api_url}}/users/edit HTTP/1.1
Content-Type: application/json

{
  "token": "{{panel_token}}",
  "app_id": "{{panel_app_id}}",
  "lang": "{{lang}}",
  "source": "{{source}}",
  "env": "{{env}}",
  "v": "{{version}}",
  "data": {
    "id": "id",
    "type": "user",
    "username": "demo",
    "password": "123456",
    "operator": 1,
    "prefix": "99450",
    "number": "1234567",
    "email": "demo.user@gmail.com",
    "fullname": "Demo User",
    "gender": "male",
    "birth": "2022-02-22",
    "avatar_id": "621508d39011e50255143533",
    "status": 2
  }
}