GET {{panel_api_url}}/categories/list
  ?token={{panel_token}}
  &app_id={{panel_app_id}}
  &lang={{lang}}
  &source={{source}}
  &env={{env}}
  &v={{version}}
  &keyword=
  &status=
  &limit=25
  &skip=0
  &sort[field]=
  &sort[order]=