POST {{api_url}}/account/changephone/step2 HTTP/1.1
Content-Type: application/json

{
  "token": "{{token}}",
  "app_id": "{{web_app_id}}",
  "lang": "{{lang}}",
  "source": "{{source}}",
  "env": "{{env}}",
  "v": "{{version}}",
  "data": {
    "hash": "b199bebac920c61644679fd1c43dfa0a",
    "code": 765917
  }
}