POST {{api_url}}/account/update HTTP/1.1
Content-Type: application/json

{
  "token": "{{token}}",
  "app_id": "{{web_app_id}}",
  "lang": "{{lang}}",
  "source": "{{source}}",
  "env": "{{env}}",
  "v": "{{version}}",
  "data": {
    "field": "set_device",
    "value": {
      "platform": "ios",
      "device_token": "a1s2d3fd4g34h5j67ujtyhregwrfa"
    }
  }
}