GET {{api_url}}/categories
  ?token={{token}}
  &app_id={{web_app_id}}
  &lang={{lang}}
  &source={{source}}
  &env={{env}}
  &v={{version}}
  &keyword=
  &limit=25
  &skip=0
  &sort[field]=title
  &sort[order]=asc